// <auto-generated />
using System;
using LibraryManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementSystem.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagementSystem.Models.Book", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Author").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Genre").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("ISBN").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<bool>("IsAvailable").HasDefaultValue(true).HasColumnType("bit");
                b.Property<string>("Title").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("ISBN").IsUnique();
                b.ToTable("Books");
            });

            modelBuilder.Entity("LibraryManagementSystem.Models.Member", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ContactInfo").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime>("MembershipDate").HasColumnType("datetime2");
                b.Property<string>("Name").IsRequired().HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.ToTable("Members");
            });

            modelBuilder.Entity("LibraryManagementSystem.Models.BorrowTransaction", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("BookId").HasColumnType("int");
                b.Property<DateTime>("BorrowDate").HasColumnType("datetime2");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime>("DueDate").HasColumnType("datetime2");
                b.Property<int>("MemberId").HasColumnType("int");
                b.Property<DateTime?>("ReturnDate").HasColumnType("datetime2");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("BookId");
                b.HasIndex("MemberId");
                b.ToTable("BorrowTransactions");
            });

            modelBuilder.Entity("LibraryManagementSystem.Models.BorrowTransaction", b =>
            {
                b.HasOne("LibraryManagementSystem.Models.Book", "Book")
                    .WithMany("Transactions").HasForeignKey("BookId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("LibraryManagementSystem.Models.Member", "Member")
                    .WithMany("Transactions").HasForeignKey("MemberId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.Navigation("Book");
                b.Navigation("Member");
            });
#pragma warning restore 612, 618
        }
    }
}
